### ISSUE TITLE
Add support for Rider

### ISSUE THREAD

**Issue by SasaCetkovic** [artemy/alfred-jetbrains-projects#26]
Rider is the only full-featured multiplatform IDE for .NET, and it recently became free for non-commercial use.

https://www.jetbrains.com/rider/

**Comment by artemy** [comment]
Thanks for reporting, @SasaCetkovic !
I've released v3.2 with Rider support https://github.com/artemy/alfred-jetbrains-projects/releases/tag/v3.2
I'll submit an update to Alfred Gallery, so it should be available there soon

Rider is a weird one, because it stores project data in a different file (`recentSolutions.xml` vs `recentProjects.xml`) and has slightly different XML file structure (`RiderRecentProjectsManager` vs `RecentProjectsManager`)

**Comment by SasaCetkovic** [comment]
Awesome, thanks!

Yeah, in Visual Studio world, a solution is a collection of projects.
