### ISSUE TITLE
Merge all IDEs workflows into one workflow and have check which ones you would like to use?

### ISSUE THREAD

**Issue by yahav01** [artemy/alfred-jetbrains-projects#8]
Is it possible to merge all IDEs workflows into one workflow and have check which ones you would like to use?

**Comment by artemy** [comment]
Hi @JamesKpP!
That's one of the ideas I've been wanting to investigate, but I haven't yet gotten to actually do it.
I'll try to find some time in September and will let you know

**Comment by gaufde** [comment]
Would it also be possible to add support for PhpStorm in the process of unifying the workflows?

**Comment by artemy** [comment]
@gaufde I evaluated a few options of unifying the workflows, but I couldn't find a solution that I liked.
I can add PhpStorm support the current way, if you like

**Comment by gaufde** [comment]
> @gaufde I evaluated a few options of unifying the workflows, but I couldn't find a solution that I liked.

I'm curious, what makes this difficult? Is retrieving the recent files from the applications, or is figuring out what applications are available, or something else altogether?

> I can add PhpStorm support the current way, if you like
That would be great!

**Comment by artemy** [comment]
> I'm curious, what makes this difficult? Is retrieving the recent files from the applications, or is figuring out what applications are available, or something else altogether?
No, it's entirely about the UX and the possibilities of Alfred. 
I would prefer that it would be possible to disable (or enable) supported apps during the workflow installation, but there's no way to do this currently, at least not without overcomplicating the mechanics of how this is put together. This makes merging all the apps into a single workflow not a convenient option in my opinion.

Maybe @vitorgalvao has a good idea for this

**Comment by artemy** [comment]
> That would be great!

@gaufde I've released PhpStorm support in v2.4, please enjoy https://github.com/artemy/alfred-jetbrains-projects/releases/tag/v2.4
And thanks for the suggestion!

**Comment by gaufde** [comment]
> @gaufde I've released PhpStorm support in v2.4, please enjoy https://github.com/artemy/alfred-jetbrains-projects/releases/tag/v2.4
And thanks for the suggestion!

Thanks a lot! I'll give it a shot :).

> I would prefer that it would be possible to disable (or enable) supported apps during the workflow installation, but there's no way to do this currently, at least not without overcomplicating the mechanics of how this is put together. This makes merging all the apps into a single workflow not a convenient option in my opinion.

Would the workflow configuration panel not solve that issue? My experience has been that I can configure workflows in the process of installing them:

<img width="1597" alt="image" src="https://github.com/user-attachments/assets/59334c3d-e4bd-411b-8e71-67e382c40ad9">

Unless I'm misunderstanding, I think some check boxes would provide the end-user experience you want:

<img width="1600" alt="image" src="https://github.com/user-attachments/assets/c8f4cacb-f80e-434d-8cdb-69ebabe38e45">  


> at least not without overcomplicating the mechanics of how this is put together.

In terms of this part, I have less experience (I'm new to developing Alfred workflows). It looks to me like you have already separated app-specific configuration details out of your code with `products.json`. Is part of the problem that you only want app-specific keywords to exist if the app is checked in the configuration? Or does the complication come from some other design goal you have?

**Comment by artemy** [comment]
> Is part of the problem that you only want app-specific keywords to exist if the app is checked in the configuration? Or does the complication come from some other design goal you have?

Yes, it's very easy to customize the configuration panel since Alfred 5, but it is not quite simple to "disable" Script Filter based on the configuration (or at all for that matter).

Actually I went to check and noticed that since [Alfred 5.5](https://www.alfredapp.com/whats-new/) variable resolution in Input object keywords is implemented, so I will look into this again. 
My idea is to let the users disable the app they don't need by making the keyword empty (which effectively will disable the respective Script Filter)

**Comment by gaufde** [comment]
> Actually I went to check and noticed that since [Alfred 5.5](https://www.alfredapp.com/whats-new/) variable resolution in Input object keywords is implemented, so I will look into this again.

Haha, I was playing around with this a bit as well! The checkboxes are booleans, so those variables wouldn't work very well as direct inputs. I started to think about ways to map the combination of checkboxes to script filter keywords, but quickly realized that "disabling" a script filter isn't possible.

> My idea is to let the users disable the app they don't need by making the keyword empty (which effectively will disable the respective Script Filter)

That makes a lot of sense! And it is a lot more simple than the path I started down. Do you care if the different inputs are imported "activated" or "deactivated" by default? Since, I'm seeing that if a default value is configured for a variable (even if it isn't required by the validation), then it will be challenging to "unset" that value. The workflow would probably have to define a non-whitespace character to use to represent empty and then do some trickery that I haven't figured out to make sure that non-whitespace character doesn't end up getting used to trigger the workflow (which I'm not even sure is possible).

<img width="947" alt="image" src="https://github.com/user-attachments/assets/000654d6-fec4-4f5a-9846-8b377822df65">

**Comment by BenjaminHerbert** [comment]
When will this be released? I was a bit confused as the README.md currently does not reflect the releases, which are still separate files.

**Comment by artemy** [comment]
Hi @BenjaminHerbert 
I'm sorry I got you confused. I'll spend some time on the next release this weekend and will submit it to the Alfred Gallery

And thanks for your sponsor donation!

**Comment by artemy** [comment]
reopening until this is released

**Comment by artemy** [comment]
released in [v3.0](https://github.com/artemy/alfred-jetbrains-projects/releases/tag/v3.0)
